sudo: required
services:
  - docker

#buildo l'immagine/i di test
before_install:
  - docker build -t gabrielescotti/react-test -f ./client/Dockerfile.dev ./client

#eseguo i test
script:
  - docker run -e CI=true gabrielescotti/react-test npm test

#creo tutte le immagini di prod
after_success:
  - docker build -t gabrielescotti/multi-client ./client
  - docker build -t gabrielescotti/multi-nginx ./nginx
  - docker build -t gabrielescotti/multi-server ./server
  - docker build -t gabrielescotti/multi-worker ./worker
  #log in al docker CLI (i valori sono presi dalle variabili d'ambiente create su travis CI)
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  #carito le immagini di prod su Docker hub
  - docker push gabrielescotti/multi-client
  - docker push gabrielescotti/multi-nginx
  - docker push gabrielescotti/multi-server
  - docker push gabrielescotti/multi-worker

deply:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-480800290578
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access-key:
    secure: $AWS_SECRET_KEY
