sudo: required
services:
  - docker

#buildo l'immagine/i di test
before_install:
  - docker build -t gabrielescotti/react-test -f ./client/Dockerfile.dev ./client

#eseguo i test
script:
  - docker run -e CI=true gabrielescotti/react-test npm test

#creo tutte le immagini di prod
after_success:
  - docker -t build gabrielescotti/multi-client ./client
  - docker -t build gabrielescotti/multi-nginx ./nginx
  - docker -t build gabrielescotti/multi-server ./server
  - docker -t build gabrielescotti/multi-worker ./worker
  #log in al docker CLI (i valori sono presi dalle variabili d'ambiente create su travis CI)
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  #carito le immagini di prod su Docker hub
  - docker push gabrielescotti/multi-client
  - docker push gabrielescotti/multi-nginx
  - docker push gabrielescotti/multi-server
  - docker push gabrielescotti/multi-worker